### PR TITLE
added installation of shared object

### PR DESCRIPTION
**Pull request by 4ludwig4**
Finally figured out how to insert the missing shared object which was an open problem for me:
```
root@dbd0868e45ac:/dev_ws# ros2 launch xiaomi_bridge xiaomi_bringup.launch.py
[INFO] [launch]: All log files can be found below ...
...
[xiaomi_bridge_node-2] /dev_ws/install/xiaomi_bridge/lib/xiaomi_bridge/xiaomi_bridge_node: error while loading shared libraries: libplayerc.so.3.1: cannot open shared object file: No such file or directory
...
```

Also added a bit of syntactic sugar. Hope the added `install` step is not totally wrong.^^

Now I got the launch file running. Now I "just" have to get my xiaomi rooted again or fix the wifi problems :D

### CODE REVIEW

**Comment by arne48** [comment]
I really like the addition of the variables.
Also the installation of the shared object makes sense.
It is strange though, I didn't have any problems with the dynamic loading of libraries so far.
Which Distro/ROS version are you using? And with which parameters are you calling "colcon build"?
What kind of WiFi problems do you have?

**Comment by 4ludwig4** [comment]
> I really like the addition of the variables.
> Also the installation of the shared object makes sense.

Cool this was quite an introduction to cmake hands-on.

> Which Distro/ROS version are you using? And with which parameters are you calling "colcon build"?

I'm also using eloquent and I think so are you since the branch is called eloquent-devel.
I'm using plain `colcon build` or do I need any flags?
 
> What kind of WiFi problems do you have?

Well it turned out my Roborock S5 is somehow not rooted anymore. Guess I have to root it again but didn't have time yet to do so. Btw which hardware version are you using also the Gen2 or the Gen1?

**Comment by arne48** [comment]
I am using a gen1 robot with a rather old firmware 003094. No particular reason for that version. I only didn't want to screw something up after it worked pretty well with ROS 1.
It's nice that you are using the S5 if we can make that one work as well, we have a second platform like the Turtlebot, and we can add another urdf file for it.
In regards to the (un)rooting issue. There seems to be a behavior, were the filesystem gets unmounted in an unclean fashion, and on the next reboot the watchdog resets the robot.
There are patches, which can be included in firmware packages now.

**Comment by arne48** [comment]
Are there any news about using a S5 with this bridge?

**Comment by 4ludwig4** [comment]
Sry didn't have time, but hopefully will do this soon as another project is getting closer to being done.

**Comment by arne48** [comment]
Got it, I was a little bit worried that the S5 turned out to be incompatible.
Take your time, and I am looking forward to feedback about this in the future.

**Pull request merged**
